### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cygon23**
they all the same why

### CODE REVIEW

**Review by intuitiversHQ — COMMENTED** [review]
Looks good 😊.
Thanks for reminding me about it.

**Comment by cygon23** [comment]
hey stuck make mine as yours bro

**Comment by cygon23** [comment]
hepl to make also mine to look pro as yours

**Comment by intuitiversHQ** [comment]
sure I'll lemme work on it.
Share details that you'd like to be added

**Comment by cygon23** [comment]
it will be gratefull

**Comment by intuitiversHQ** [comment]
but you should be patient, I'll definitely make it as yours, share with me what features you want to be there, or I should make it as I can?

**Comment by cygon23** [comment]
technologies that am capble of are React js,Reactnative,LARVALEL, html,css,bootscramp,python in small amount , os linux and windows,specificacally based in offensive side and some styling that are not much it will thankful

**Pull request merged**
